version: '3.9'
services:
  db:
    image: postgres:14
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: edisu
      POSTGRES_USER: pg
      POSTGRES_PASSWORD: pg
    volumes:
      - ./var/pg:/var/lib/postgresql/data:delegated
